development:
  adapter: mysql2
  encoding: utf8
  database: "s383939_okon"
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
test:
  adapter: mysql2
  encoding: utf8
  database: "s383939_okon"
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
  database: "s383939_okon"
  pool: 5
  username: "s383939"
  password: "NaszaBaza12"
  host: "mysql.wmi.amu.edu.pl"
  port: 3306
